# MySQL ?? ??
spring.datasource.url=jdbc:mysql://localhost:3306/maywave?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=wnstn4304!

# JPA ?? (??? ?? ?? ? SQL ?? ??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL 8 ?? ??
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Gemini API
gemini.api-key=AIzaSyDtt9xOneS-TtkpvxxKTvLKaGzb8vbUgQg
gemini.base-url=https://generativelanguage.googleapis.com/v1beta
gemini.model=gemini-3.1-flash-lite-preview
